# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis_importer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcgislayerimport',
            name='layername',
        ),
    ]
