# Generated by Django 2.2.16 on 2021-01-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis_importer', '0002_remove_arcgislayerimport_layername'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Esri Feature Layer URL Example: https://xxx/ArcGIS/rest/services/xxx/xxx/MapServer/0', verbose_name='Layer URL')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='name')),
                ('last_update_status', models.CharField(blank=True, choices=[('Failed', 'Failed'), ('Succeeded', 'Succeeded')], max_length=128, null=True, verbose_name='Last Update Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
